### PR TITLE
More reviews

### PR DESCRIPTION
**Pull request by davevs**
Not sure if all comments are actually in the right sections, but I added them where I was triggered to add them.

### CODE REVIEW

**Comment by DinisCruz** [comment]
Hi, thanks again.

One thing, these changes are conflicting because you need to pull the changes from my master

image

I'm going to try to merge it and keep your new changes

**Comment by DinisCruz** [comment]
Hi all changes merged, as mentioned on twitter, can you double check that all your changes are on this commit https://github.com/DinisCruz/Book_Jira_Risk_Workflow/commit/8918faff6ad59e0cffac3d282d4bb47dc3b3d33b ?

thx

**Comment by davevs** [comment]
I already replied on twitter; as far as I can see everything is there.
Just to be sure; is the feedback until now more or less what you were looking for?

**Comment by DinisCruz** [comment]
yeah man it's great :)

I also like that it allows me to expand on the topics you're covering and refactor the text a bit

**Comment by DinisCruz** [comment]
btw if you want to see what the final PDF is looking like, you can see the released versions at https://github.com/DinisCruz/Book_Jira_Risk_Workflow/releases (which is the same that you get from leanpub)
(every time there is a good number of changes I publish a release)

**Pull request merged**
